apiVersion: v1
kind: Pod
metadata:
  name:  memory-demo
  namespace: test #指定命名空间
spec: #定义期望状态
  containers:
    - name:  memory-demo-ctr
      image:  polinux/stress
      resources:
        limits: 
          memory: "200Mi" #限制内存大小 限制在200以内
        requests:
          memory: "100Mi" #请求内存大小 初始化时100
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"] #尝试分配150内存

        

    