apiVersion: v1
kind: Pod
metadata:
  name: test-secret-volume-pod
spec:
  containers:
  - image:  busybox
    name:  text-secret-volume
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name:  mysql-card
      mountPath:  "/projected-volume"
  volumes:
  - name:  mysql-card
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass