apiVersion: v1
kind: Endpoints
metadata:
    labels:
      app.kubernetes.io/name: kube-scheduler
    name: kube-scheduler-monitor
    namespace: kube-system
subsets:
  - addresses:
    - ip: 10.1.140.24
    ports:
    - name: https-metrics
      port: 10251
      protocol: TCP