apiVersion: v1
kind: Endpoints
metadata:
    labels:
      app.kubernetes.io/name: kube-proxy
    name: kube-proxy-monitor
    namespace: kube-system
subsets:
  - addresses:
    - ip: 10.1.140.24
    - ip: 10.1.140.25
    - ip: 10.1.140.26
    ports:
    - name: https-metrics
      port: 10249
      protocol: TCP