apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-proxy
  name: kube-proxy-monitor
  namespace: kube-system
spec:
  ports:
  - name: https-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  sessionAffinity: None
  type: ClusterIP