kind: Service
apiVersion: v1
metadata:
  name:  mysql
  labels:
    app: mysql
spec:
  selector:
    app:  mysql
  clusterIP: None
  ports:
  - name:  mysql
    port:  3306
---
kind: Service
apiVersion: v1
metadata:
  name:  mysql-read
  labels:
    app: mysql
spec:
  selector:
    app:  mysql
  ports:
  - name:  mysql
    port:  3306