apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name:  redis
    image: redis
    volumeMounts:
    - name:  redis-storage
      mountPath: /data/redis
    - name: redis-hostpath
      mountPath: /data/hostpath      
  volumes:
  - name:  redis-storage
    emptyDir: {}
  - name: redis-hostpath
    hostPath: 
      path: /opt/software/k8s-demo/data
      type: File
