apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name:  nginx
    image: nginx
    volumeMounts:
    - name:  nginx-storage
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: nginx-storage
    nfs:
     server: 10.1.140.26
     path: /data/nfs/nginx
