kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: single-role-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: single-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: single-role
  apiGroup: rbac.authorization.k8s.io