apiVersion: v1
kind: Pod
metadata:
  name: ceph-fs-pod
spec:
  containers:
  - image:  nginx
    name:  nginx-node1
    volumeMounts:
    - name:  ceph-fs-volume
      mountPath:  "/usr/share/nginx/html"
  - image:  nginx
    name:  nginx-node2
    volumeMounts:
    - name:  ceph-fs-volume
      mountPath:  "/usr/share/nginx/html"
  volumes:
  - name: ceph-fs-volume
    persistentVolumeClaim:
      claimName:  cephfs-pvc