apiVersion: v1
kind: Pod
metadata:
  name: ceph-fs-pod
spec:
  containers:
  - image:  nginx
    name:  nginx-node1
    volumeMounts:
    - name:  ceph-fs-volume
      mountPath:  "/usr/share/nginx/html"
    ports:
      - containerPort: 80
        name: "http-server"
  - image:  nginx
    name:  nginx-node2
    volumeMounts:
    - name:  ceph-fs-volume
      mountPath:  "/usr/share/nginx/html"
    ports:
      - containerPort: 81
        name: "http-server"
  volumes:
  - name: ceph-fs-volume
    persistentVolumeClaim:
      claimName:  cephfs-pvc