apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blick-sc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  